print("Сніцаренко Анна Сергіївна \nКМ-91 \nЛабораторна робота №1 \nЗнайти max {min (a, b), min (c, d)} \n")
a = float(input("Введіть значення a"))
b = float(input("Введіть значення b"))
c = float(input("Введіть значення c"))
d = float(input("Введіть значення d"))
print(max(min(a, b), min(c, d)))